{% set version = "1.3.1" %}

package:
  name: ptrimmer
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/DMU-lilab/pTrimmer/archive/48eaccf3bd3bb5c3cfc770699eb994d0456b3fb2.tar.gz
  sha256: 1b15f4f24ecc239f1ea2a39b1bb111b6e1d80f0d

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - ncurses
    - zlib
  run:
    - ncurses
    - zlib

about:
  home: https://github.com/DMU-lilab/pTrimmer
  license: GPL-3.0
  license_file: LICENSE
  summary: Used to trim off the primer sequence from mutiplex amplicon sequencing

test:
  commands:
    - ptrimmer --help