{% set version = "0.1.0" %}

package:
  name: hitea
  version: {{ version }}

source:
  url: https://github.com/parklab/HiTea/archive/{{ version }}.tar.gz
  md5: b3bf4f4c8c706d1f149e911b1bda407a

build:
  number: 0

requirements:
  host:
    - python
    - pairtools
    - bioconductor-genomicranges
    - bioconductor-enrichedheatmap
  run:
    - python
    - pairtools
    - bioconductor-genomicranges
    - bioconductor-enrichedheatmap

test:
  imports:
    - pairtools
  commands:
    - hitea
    - . test.sh

about:
  home: https://github.com/parklab/HiTea
  license: MIT
  license_file: "LICENSE.txt"
  summary: computational tool to identify trasposable element insertions using Hi-C data
  license_family: MIT
