{% set version = "0.1.0" %}

package:
  name: hitea
  version: {{ version }}

source:
  url: https://github.com/parklab/HiTea/archive/{{ version }}.tar.gz
  md5: a1f9b3c7b13d904dfe736cf5e66c2385

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - R
  host:
    - python
    - pairtools
    - bioconductor-all
  run:
    - htslib
    - python
    - pairtools
    - bioconductor-all

test:
  imports:
    - pairtools
  commands:
    - hitea

about:
  home: https://github.com/parklab/HiTea
  license: MIT
  license_file: "LICENSE.txt"
  summary: computational tool to identify trasposable element insertions using Hi-C data
  license_family: MIT
